---
platform: linux

#image_resource:
#  type: docker-image
#  source: {repository: ukbieso/ejm}

inputs:
  - name: java-test

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |
    chmod +x java-test/ci/build.sh
    ./java-test/ci/build.sh sleep 10s
